// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GeocodeData, GeocodeErrors, GeocodeResponses, InitialData, InitialErrors, InitialResponses, LevelsData, LevelsErrors, LevelsResponses, OneToAllData, OneToAllErrors, OneToAllResponses, OneToManyData, OneToManyErrors, OneToManyIntermodalData, OneToManyIntermodalErrors, OneToManyIntermodalPostData, OneToManyIntermodalPostErrors, OneToManyIntermodalPostResponses, OneToManyIntermodalResponses, OneToManyPostData, OneToManyPostErrors, OneToManyPostResponses, OneToManyResponses, PlanData, PlanErrors, PlanResponses, RentalsData, RentalsErrors, RentalsResponses, ReverseGeocodeData, ReverseGeocodeErrors, ReverseGeocodeResponses, RoutesData, RoutesErrors, RoutesResponses, StopsData, StopsErrors, StopsResponses, StoptimesData, StoptimesErrors, StoptimesResponses, TransfersData, TransfersResponses, TripData, TripErrors, TripResponses, TripsData, TripsErrors, TripsResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Computes optimal connections from one place to another.
 */
export const plan = <ThrowOnError extends boolean = false>(options: Options<PlanData, ThrowOnError>) => (options.client ?? client).get<PlanResponses, PlanErrors, ThrowOnError>({
    querySerializer: { parameters: {
            via: { array: { explode: false } },
            viaMinimumStay: { array: { explode: false } },
            transitModes: { array: { explode: false } },
            directModes: { array: { explode: false } },
            preTransitModes: { array: { explode: false } },
            postTransitModes: { array: { explode: false } },
            directRentalFormFactors: { array: { explode: false } },
            preTransitRentalFormFactors: { array: { explode: false } },
            postTransitRentalFormFactors: { array: { explode: false } },
            directRentalPropulsionTypes: { array: { explode: false } },
            preTransitRentalPropulsionTypes: { array: { explode: false } },
            postTransitRentalPropulsionTypes: { array: { explode: false } },
            directRentalProviders: { array: { explode: false } },
            directRentalProviderGroups: { array: { explode: false } },
            preTransitRentalProviders: { array: { explode: false } },
            preTransitRentalProviderGroups: { array: { explode: false } },
            postTransitRentalProviders: { array: { explode: false } },
            postTransitRentalProviderGroups: { array: { explode: false } },
            language: { array: { explode: false } }
        } },
    url: '/api/v5/plan',
    ...options
});

/**
 * Street routing from one to many places or many to one.
 * The order in the response array corresponds to the order of coordinates of the \`many\` parameter in the query.
 *
 */
export const oneToMany = <ThrowOnError extends boolean = false>(options: Options<OneToManyData, ThrowOnError>) => (options.client ?? client).get<OneToManyResponses, OneToManyErrors, ThrowOnError>({
    querySerializer: { parameters: { many: { array: { explode: false } } } },
    url: '/api/v1/one-to-many',
    ...options
});

/**
 * Street routing from one to many places or many to one.
 * The order in the response array corresponds to the order of coordinates of the \`many\` parameter in the request body.
 *
 */
export const oneToManyPost = <ThrowOnError extends boolean = false>(options: Options<OneToManyPostData, ThrowOnError>) => (options.client ?? client).post<OneToManyPostResponses, OneToManyPostErrors, ThrowOnError>({
    url: '/api/v1/one-to-many',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * One to many routing
 * Computes the minimal duration from one place to many or vice versa.
 * The order in the response array corresponds to the order of coordinates of the \`many\` parameter in the query.
 *
 */
export const oneToManyIntermodal = <ThrowOnError extends boolean = false>(options: Options<OneToManyIntermodalData, ThrowOnError>) => (options.client ?? client).get<OneToManyIntermodalResponses, OneToManyIntermodalErrors, ThrowOnError>({
    querySerializer: { parameters: {
            many: { array: { explode: false } },
            transitModes: { array: { explode: false } },
            preTransitModes: { array: { explode: false } },
            postTransitModes: { array: { explode: false } }
        } },
    url: '/api/experimental/one-to-many-intermodal',
    ...options
});

/**
 * One to many routing
 * Computes the minimal duration from one place to many or vice versa.
 * The order in the response array corresponds to the order of coordinates of the \`many\` parameter in the request body.
 *
 */
export const oneToManyIntermodalPost = <ThrowOnError extends boolean = false>(options: Options<OneToManyIntermodalPostData, ThrowOnError>) => (options.client ?? client).post<OneToManyIntermodalPostResponses, OneToManyIntermodalPostErrors, ThrowOnError>({
    url: '/api/experimental/one-to-many-intermodal',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Computes all reachable locations from a given stop within a set duration.
 * Each result entry will contain the fastest travel duration and the number of connections used.
 *
 */
export const oneToAll = <ThrowOnError extends boolean = false>(options: Options<OneToAllData, ThrowOnError>) => (options.client ?? client).get<OneToAllResponses, OneToAllErrors, ThrowOnError>({
    querySerializer: { parameters: {
            transitModes: { array: { explode: false } },
            preTransitModes: { array: { explode: false } },
            postTransitModes: { array: { explode: false } }
        } },
    url: '/api/v1/one-to-all',
    ...options
});

/**
 * Translate coordinates to the closest address(es)/places/stops.
 */
export const reverseGeocode = <ThrowOnError extends boolean = false>(options: Options<ReverseGeocodeData, ThrowOnError>) => (options.client ?? client).get<ReverseGeocodeResponses, ReverseGeocodeErrors, ThrowOnError>({ url: '/api/v1/reverse-geocode', ...options });

/**
 * Autocompletion & geocoding that resolves user input addresses including coordinates
 */
export const geocode = <ThrowOnError extends boolean = false>(options: Options<GeocodeData, ThrowOnError>) => (options.client ?? client).get<GeocodeResponses, GeocodeErrors, ThrowOnError>({
    querySerializer: { parameters: { language: { array: { explode: false } }, mode: { array: { explode: false } } } },
    url: '/api/v1/geocode',
    ...options
});

/**
 * Get a trip as itinerary
 */
export const trip = <ThrowOnError extends boolean = false>(options: Options<TripData, ThrowOnError>) => (options.client ?? client).get<TripResponses, TripErrors, ThrowOnError>({
    querySerializer: { parameters: { language: { array: { explode: false } } } },
    url: '/api/v5/trip',
    ...options
});

/**
 * Get the next N departures or arrivals of a stop sorted by time
 */
export const stoptimes = <ThrowOnError extends boolean = false>(options?: Options<StoptimesData, ThrowOnError>) => (options?.client ?? client).get<StoptimesResponses, StoptimesErrors, ThrowOnError>({
    querySerializer: { parameters: { mode: { array: { explode: false } }, language: { array: { explode: false } } } },
    url: '/api/v5/stoptimes',
    ...options
});

/**
 * Given a area frame (box defined by top right and bottom left corner) and a time frame,
 * it returns all trips and their respective shapes that operate in this area + time frame.
 * Trips are filtered by zoom level. On low zoom levels, only long distance trains will be shown
 * while on high zoom levels, also metros, buses and trams will be returned.
 *
 */
export const trips = <ThrowOnError extends boolean = false>(options: Options<TripsData, ThrowOnError>) => (options.client ?? client).get<TripsResponses, TripsErrors, ThrowOnError>({
    querySerializer: { parameters: { language: { array: { explode: false } } } },
    url: '/api/v5/map/trips',
    ...options
});

/**
 * initial location to view the map at after loading based on where public transport should be visible
 */
export const initial = <ThrowOnError extends boolean = false>(options?: Options<InitialData, ThrowOnError>) => (options?.client ?? client).get<InitialResponses, InitialErrors, ThrowOnError>({ url: '/api/v1/map/initial', ...options });

/**
 * Get all stops for a map section
 */
export const stops = <ThrowOnError extends boolean = false>(options: Options<StopsData, ThrowOnError>) => (options.client ?? client).get<StopsResponses, StopsErrors, ThrowOnError>({
    querySerializer: { parameters: { language: { array: { explode: false } } } },
    url: '/api/v1/map/stops',
    ...options
});

/**
 * Get all available levels for a map section
 */
export const levels = <ThrowOnError extends boolean = false>(options: Options<LevelsData, ThrowOnError>) => (options.client ?? client).get<LevelsResponses, LevelsErrors, ThrowOnError>({ url: '/api/v1/map/levels', ...options });

/**
 * Given an area frame (box defined by the top-right and bottom-left corners),
 * it returns all routes and their respective shapes that operate within this area.
 * Routes are filtered by zoom level. On low zoom levels, only long distance trains will be shown
 * while on high zoom levels, also metros, buses and trams will be returned.
 *
 */
export const routes = <ThrowOnError extends boolean = false>(options: Options<RoutesData, ThrowOnError>) => (options.client ?? client).get<RoutesResponses, RoutesErrors, ThrowOnError>({
    querySerializer: { parameters: { language: { array: { explode: false } } } },
    url: '/api/experimental/map/routes',
    ...options
});

/**
 * Get a list of rental providers or all rental stations and vehicles for
 * a map section or provider
 *
 *
 * Various options to filter the providers, stations and vehicles are
 * available. If none of these filters are provided, a list of all
 * available rental providers is returned without any station, vehicle or
 * zone data.
 *
 * At least one of the following filters must be provided to retrieve
 * station, vehicle and zone data:
 *
 * - A bounding box defined by the `min` and `max` parameters
 * - A circle defined by the `point` and `radius` parameters
 * - A list of provider groups via the `providerGroups` parameter
 * - A list of providers via the `providers` parameter
 *
 * Only data that matches all the provided filters is returned.
 *
 * Provide the `withProviders=false` parameter to retrieve only provider
 * groups if detailed feed information is not required.
 *
 */
export const rentals = <ThrowOnError extends boolean = false>(options?: Options<RentalsData, ThrowOnError>) => (options?.client ?? client).get<RentalsResponses, RentalsErrors, ThrowOnError>({
    querySerializer: { parameters: { providerGroups: { array: { explode: false } }, providers: { array: { explode: false } } } },
    url: '/api/v1/rentals',
    ...options
});

/**
 * Prints all transfers of a timetable location (track, bus stop, etc.)
 */
export const transfers = <ThrowOnError extends boolean = false>(options: Options<TransfersData, ThrowOnError>) => (options.client ?? client).get<TransfersResponses, unknown, ThrowOnError>({ url: '/api/debug/transfers', ...options });
